; =============================================================
;  MediDispense — PlatformIO Config
;  Board: Heltec WiFi LoRa 32 V3
; =============================================================

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  sandeepmistry/LoRa @ ^0.8.0
  adafruit/Adafruit Fingerprint Sensor Library @ ^2.0.3
  adafruit/RTClib @ ^2.1.1
  madhephaestus/ESP32Servo @ ^3.0.0
  bblanchon/ArduinoJson @ ^7.0.0
  olikraus/U8g2 @ ^2.35.7

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DBOARD_HAS_PSRAM

[platformio]
default_envs = heltec_wifi_lora_32_V3
